apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: review-bot-monitor
  namespace: review-bot
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: review-bot
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
  namespaceSelector:
    matchNames:
      - review-bot
