apiVersion: v1
kind: Service
metadata:
  name: review-bot
  namespace: review-bot
  labels:
    app: review-bot
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: review-bot
